// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#ifndef _DASHBOARD_UI_H
#define _DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_ScreenHome.h"
#include "screens/ui_ScreenNAS.h"
#include "screens/ui_ScreenFreebox.h"
#include "screens/ui_ScreenTable.h"
#include "screens/ui_ScreenAI.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_Font10);
LV_FONT_DECLARE( ui_font_Font12);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
