// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void display_show_TABLE_NAS_DISKS(lv_event_t * e);
void display_show_TABLE_FBX_DEVICES(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
