// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#include "ui.h"

void on_edit_ssid(lv_event_t * e)
{
	// Your code here
}

void on_edit_password(lv_event_t * e)
{
	// Your code here
}

void on_edit_mqtt_port(lv_event_t * e)
{
	// Your code here
}

void settings_keyboard_confirm(lv_event_t * e)
{
	// Your code here
}

void on_ta_ssid_clicked(lv_event_t * e)
{
	// Your code here
}

void on_ta_password_clicked(lv_event_t * e)
{
	// Your code here
}

void on_ta_mqtt_ip_clicked(lv_event_t * e)
{
	// Your code here
}

void on_ta_mqtt_port_clicked(lv_event_t * e)
{
	// Your code here
}

void on_btn_save_clicked(lv_event_t * e)
{
	// Your code here
}

void display_show_tableTABLE_NAS_DISKS(lv_event_t * e)
{
	// Your code here
}

void display_show_tableTABLE_FBX_DEVICES(lv_event_t * e)
{
	// Your code here
}

// display_show_TABLE_NAS_DISKS / display_show_TABLE_FBX_DEVICES : stubs SquareLine
// vides RETIRÉS — l'implémentation réelle vit dans display_manager.cpp (même nom,
// sinon erreur de symbole dupliqué au lien). ATTENTION : SquareLine les régénère
// à chaque export de l'UI — il faut les re-retirer après (ou automatiser, cf.
// discussion). Idem pour le doublon assets/ui_font_Font12.c.

void display_show_TABLE_NAS_DISKS(lv_event_t * e)
{
	// Your code here
}

void display_show_TABLE_FBX_DEVICES(lv_event_t * e)
{
	// Your code here
}
