// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#ifndef UI_SCREENAI_H
#define UI_SCREENAI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAI
extern void ui_ScreenAI_screen_init(void);
extern void ui_ScreenAI_screen_destroy(void);
extern lv_obj_t *ui_ScreenAI;
extern void ui_event_BtnBackAI( lv_event_t * e);
extern lv_obj_t *ui_BtnBackAI;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_BtnPlayAI;
extern lv_obj_t *ui_LabelPlay;
extern lv_obj_t *ui_BtnRecAI;
extern lv_obj_t *ui_LabelRec;
extern lv_obj_t *ui_LabelQuestion;
extern lv_obj_t *ui_LabelAnswer;
extern lv_obj_t *ui_ImageCompanion;
extern lv_obj_t *ui_LabelFeebox2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

