// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#ifndef UI_SCREENFREEBOX_H
#define UI_SCREENFREEBOX_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenFreebox
extern void ui_ScreenFreebox_screen_init(void);
extern void ui_ScreenFreebox_screen_destroy(void);
extern lv_obj_t *ui_ScreenFreebox;
extern lv_obj_t *ui_LabelFeebox;
extern void ui_event_BtnBackFbx( lv_event_t * e);
extern lv_obj_t *ui_BtnBackFbx;
extern lv_obj_t *ui_Label12;
extern void ui_event_BtnNextFbx( lv_event_t * e);
extern lv_obj_t *ui_BtnNextFbx;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_LabelFbDown;
extern lv_obj_t *ui_LabelFbUp;
extern lv_obj_t *ui_LabelFbBwDown;
extern lv_obj_t *ui_LabelFbBwUp;
extern lv_obj_t *ui_LabelFbState;
extern lv_obj_t *ui_LabelFbIPv4;
extern lv_obj_t *ui_LabelFbDevicesActive;
extern lv_obj_t *ui_LabelFbDevicesTotal;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

