// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#include "../ui.h"

lv_obj_t *ui_ScreenHome = NULL;lv_obj_t *ui_BtnNAS = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_BtnFreebox = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_BtnSysInfo = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_BtnAI = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_BtnLight = NULL;lv_obj_t *ui_LabelLight = NULL;lv_obj_t *ui_SliderLCD = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_BtnAudio = NULL;lv_obj_t *ui_Label18 = NULL;lv_obj_t *ui_SliderVOL = NULL;lv_obj_t *ui_Label9 = NULL;
// event funtions
void ui_event_BtnNAS( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenNAS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenNAS_screen_init);
}
}

void ui_event_BtnFreebox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenFreebox, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenFreebox_screen_init);
}
}

void ui_event_BtnAI( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenAI, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenAI_screen_init);
}
}

// build funtions

void ui_ScreenHome_screen_init(void)
{
ui_ScreenHome = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnNAS = lv_button_create(ui_ScreenHome);
lv_obj_set_width( ui_BtnNAS, 140);
lv_obj_set_height( ui_BtnNAS, 45);
lv_obj_set_x( ui_BtnNAS, 10 );
lv_obj_set_y( ui_BtnNAS, 10 );
lv_obj_set_ext_click_area(ui_BtnNAS, 5);
lv_obj_add_flag( ui_BtnNAS, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnNAS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_BtnNAS, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_BtnNAS);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"NAS");

ui_BtnFreebox = lv_button_create(ui_ScreenHome);
lv_obj_set_width( ui_BtnFreebox, 140);
lv_obj_set_height( ui_BtnFreebox, 45);
lv_obj_set_x( ui_BtnFreebox, 170 );
lv_obj_set_y( ui_BtnFreebox, 10 );
lv_obj_set_ext_click_area(ui_BtnFreebox, 5);
lv_obj_add_flag( ui_BtnFreebox, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnFreebox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_BtnFreebox, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_BtnFreebox);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Freebox");

ui_BtnSysInfo = lv_button_create(ui_ScreenHome);
lv_obj_set_width( ui_BtnSysInfo, 140);
lv_obj_set_height( ui_BtnSysInfo, 45);
lv_obj_set_x( ui_BtnSysInfo, 10 );
lv_obj_set_y( ui_BtnSysInfo, 70 );
lv_obj_set_ext_click_area(ui_BtnSysInfo, 5);
lv_obj_add_flag( ui_BtnSysInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnSysInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_BtnSysInfo, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_BtnSysInfo);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"SysInfo");

ui_BtnAI = lv_button_create(ui_ScreenHome);
lv_obj_set_width( ui_BtnAI, 140);
lv_obj_set_height( ui_BtnAI, 45);
lv_obj_set_x( ui_BtnAI, 170 );
lv_obj_set_y( ui_BtnAI, 70 );
lv_obj_set_ext_click_area(ui_BtnAI, 5);
lv_obj_add_flag( ui_BtnAI, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnAI, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_BtnAI, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_BtnAI);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Companion IA");

ui_BtnLight = lv_button_create(ui_ScreenHome);
lv_obj_set_width( ui_BtnLight, 90);
lv_obj_set_height( ui_BtnLight, 45);
lv_obj_set_x( ui_BtnLight, 220 );
lv_obj_set_y( ui_BtnLight, 130 );
lv_obj_add_flag( ui_BtnLight, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnLight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_BtnLight, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelLight = lv_label_create(ui_BtnLight);
lv_obj_set_width( ui_LabelLight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelLight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelLight, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelLight,"Auto");

ui_SliderLCD = lv_slider_create(ui_ScreenHome);
lv_slider_set_value( ui_SliderLCD, 20, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderLCD)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderLCD, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderLCD, 200);
lv_obj_set_height( ui_SliderLCD, 30);
lv_obj_set_x( ui_SliderLCD, 10 );
lv_obj_set_y( ui_SliderLCD, 140 );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_SliderLCD,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_SliderLCD, lv_obj_get_style_pad_right(ui_SliderLCD,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label3 = lv_label_create(ui_SliderLCD);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Backlight");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnAudio = lv_button_create(ui_ScreenHome);
lv_obj_set_width( ui_BtnAudio, 90);
lv_obj_set_height( ui_BtnAudio, 45);
lv_obj_set_x( ui_BtnAudio, 220 );
lv_obj_set_y( ui_BtnAudio, 185 );
lv_obj_add_flag( ui_BtnAudio, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnAudio, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_BtnAudio, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_BtnAudio);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"Test Audio");

ui_SliderVOL = lv_slider_create(ui_ScreenHome);
lv_slider_set_value( ui_SliderVOL, 60, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderVOL)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderVOL, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderVOL, 200);
lv_obj_set_height( ui_SliderVOL, 30);
lv_obj_set_x( ui_SliderVOL, 10 );
lv_obj_set_y( ui_SliderVOL, 190 );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_SliderVOL,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_SliderVOL, lv_obj_get_style_pad_right(ui_SliderVOL,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label9 = lv_label_create(ui_SliderVOL);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Volume");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BtnNAS, ui_event_BtnNAS, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnFreebox, ui_event_BtnFreebox, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnAI, ui_event_BtnAI, LV_EVENT_ALL, NULL);

}

void ui_ScreenHome_screen_destroy(void)
{
   if (ui_ScreenHome) lv_obj_del(ui_ScreenHome);

// NULL screen variables
ui_ScreenHome= NULL;
ui_BtnNAS= NULL;
ui_Label1= NULL;
ui_BtnFreebox= NULL;
ui_Label4= NULL;
ui_BtnSysInfo= NULL;
ui_Label7= NULL;
ui_BtnAI= NULL;
ui_Label10= NULL;
ui_BtnLight= NULL;
ui_LabelLight= NULL;
ui_SliderLCD= NULL;
ui_Label3= NULL;
ui_BtnAudio= NULL;
ui_Label18= NULL;
ui_SliderVOL= NULL;
ui_Label9= NULL;

}
