// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHome
extern void ui_ScreenHome_screen_init(void);
extern void ui_ScreenHome_screen_destroy(void);
extern lv_obj_t *ui_ScreenHome;
extern void ui_event_BtnNAS( lv_event_t * e);
extern lv_obj_t *ui_BtnNAS;
extern lv_obj_t *ui_Label1;
extern void ui_event_BtnFreebox( lv_event_t * e);
extern lv_obj_t *ui_BtnFreebox;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_BtnSysInfo;
extern lv_obj_t *ui_Label7;
extern void ui_event_BtnAI( lv_event_t * e);
extern lv_obj_t *ui_BtnAI;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_BtnLight;
extern lv_obj_t *ui_LabelLight;
extern lv_obj_t *ui_SliderLCD;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_BtnAudio;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_SliderVOL;
extern lv_obj_t *ui_Label9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

