// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#include "../ui.h"

lv_obj_t *ui_ScreenAI = NULL;lv_obj_t *ui_BtnBackAI = NULL;lv_obj_t *ui_Label19 = NULL;lv_obj_t *ui_BtnPlayAI = NULL;lv_obj_t *ui_LabelPlay = NULL;lv_obj_t *ui_BtnRecAI = NULL;lv_obj_t *ui_LabelRec = NULL;lv_obj_t *ui_LabelQuestion = NULL;lv_obj_t *ui_LabelAnswer = NULL;lv_obj_t *ui_ImageCompanion = NULL;lv_obj_t *ui_LabelFeebox2 = NULL;
// event funtions
void ui_event_BtnBackAI( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
}
}

// build funtions

void ui_ScreenAI_screen_init(void)
{
ui_ScreenAI = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenAI, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnBackAI = lv_button_create(ui_ScreenAI);
lv_obj_set_width( ui_BtnBackAI, 60);
lv_obj_set_height( ui_BtnBackAI, 30);
lv_obj_set_align( ui_BtnBackAI, LV_ALIGN_TOP_RIGHT );
lv_obj_set_ext_click_area(ui_BtnBackAI, 10);
lv_obj_add_flag( ui_BtnBackAI, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnBackAI, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label19 = lv_label_create(ui_BtnBackAI);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"Home");

ui_BtnPlayAI = lv_button_create(ui_ScreenAI);
lv_obj_set_width( ui_BtnPlayAI, 60);
lv_obj_set_height( ui_BtnPlayAI, 30);
lv_obj_set_x( ui_BtnPlayAI, 260 );
lv_obj_set_y( ui_BtnPlayAI, 80 );
lv_obj_set_ext_click_area(ui_BtnPlayAI, 20);
lv_obj_add_flag( ui_BtnPlayAI, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnPlayAI, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPlay = lv_label_create(ui_BtnPlayAI);
lv_obj_set_width( ui_LabelPlay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPlay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelPlay, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPlay,"Play");

ui_BtnRecAI = lv_button_create(ui_ScreenAI);
lv_obj_set_width( ui_BtnRecAI, 60);
lv_obj_set_height( ui_BtnRecAI, 30);
lv_obj_set_x( ui_BtnRecAI, 0 );
lv_obj_set_y( ui_BtnRecAI, 80 );
lv_obj_set_ext_click_area(ui_BtnRecAI, 20);
lv_obj_add_flag( ui_BtnRecAI, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnRecAI, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelRec = lv_label_create(ui_BtnRecAI);
lv_obj_set_width( ui_LabelRec, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRec, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelRec, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelRec,"Rec");

ui_LabelQuestion = lv_label_create(ui_ScreenAI);
lv_obj_set_width( ui_LabelQuestion, 320);
lv_obj_set_height( ui_LabelQuestion, 30);
lv_obj_set_x( ui_LabelQuestion, 0 );
lv_obj_set_y( ui_LabelQuestion, 10 );
lv_obj_set_align( ui_LabelQuestion, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelQuestion,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_LabelQuestion,"Question\n");
lv_obj_add_flag( ui_LabelQuestion, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_LabelQuestion, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_LabelQuestion, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelQuestion, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelQuestion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelQuestion, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAnswer = lv_label_create(ui_ScreenAI);
lv_obj_set_width( ui_LabelAnswer, 320);
lv_obj_set_height( ui_LabelAnswer, 90);
lv_obj_set_x( ui_LabelAnswer, 0 );
lv_obj_set_y( ui_LabelAnswer, 70 );
lv_obj_set_align( ui_LabelAnswer, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAnswer,"Réponse");
lv_obj_add_flag( ui_LabelAnswer, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_LabelAnswer, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_align(ui_LabelAnswer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelAnswer, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageCompanion = lv_image_create(ui_ScreenAI);
lv_obj_set_width( ui_ImageCompanion, 120);
lv_obj_set_height( ui_ImageCompanion, 120);
lv_obj_set_align( ui_ImageCompanion, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_ImageCompanion, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelFeebox2 = lv_label_create(ui_ScreenAI);
lv_obj_set_width( ui_LabelFeebox2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFeebox2, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelFeebox2,"Jarvis");
lv_obj_set_style_text_font(ui_LabelFeebox2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BtnBackAI, ui_event_BtnBackAI, LV_EVENT_ALL, NULL);

}

void ui_ScreenAI_screen_destroy(void)
{
   if (ui_ScreenAI) lv_obj_del(ui_ScreenAI);

// NULL screen variables
ui_ScreenAI= NULL;
ui_BtnBackAI= NULL;
ui_Label19= NULL;
ui_BtnPlayAI= NULL;
ui_LabelPlay= NULL;
ui_BtnRecAI= NULL;
ui_LabelRec= NULL;
ui_LabelQuestion= NULL;
ui_LabelAnswer= NULL;
ui_ImageCompanion= NULL;
ui_LabelFeebox2= NULL;

}
