// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#ifndef UI_SCREENNAS_H
#define UI_SCREENNAS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenNAS
extern void ui_ScreenNAS_screen_init(void);
extern void ui_ScreenNAS_screen_destroy(void);
extern lv_obj_t *ui_ScreenNAS;
extern lv_obj_t *ui_LabelTitleNAS;
extern void ui_event_BtnBackNAS( lv_event_t * e);
extern lv_obj_t *ui_BtnBackNAS;
extern lv_obj_t *ui_Label6;
extern void ui_event_BtnNextNAS( lv_event_t * e);
extern lv_obj_t *ui_BtnNextNAS;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_ArcNASCPU;
extern lv_obj_t *ui_LabelNASCPU;
extern lv_obj_t *ui_LabelTitleCPU;
extern lv_obj_t *ui_ArcNASRAM;
extern lv_obj_t *ui_LabelNASRAM;
extern lv_obj_t *ui_LabelTitleRAM;
extern lv_obj_t *ui_LabelNASTemp;
extern lv_obj_t *ui_LabelNASVol;
extern lv_obj_t *ui_LabelNASVolStatus;
extern lv_obj_t *ui_LabelNASNetRx;
extern lv_obj_t *ui_LabelNASNetTx;
extern lv_obj_t *ui_LabelNASVolRead;
extern lv_obj_t *ui_LabelNASVolWrite;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenNAS;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

