// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#ifndef UI_SCREENTABLE_H
#define UI_SCREENTABLE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenTable
extern void ui_ScreenTable_screen_init(void);
extern void ui_ScreenTable_screen_destroy(void);
extern lv_obj_t *ui_ScreenTable;
extern lv_obj_t *ui_BtnBackTable;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_BtnNextTable;
extern lv_obj_t *ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

