// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#include "../ui.h"

lv_obj_t *ui_ScreenFreebox = NULL;lv_obj_t *ui_LabelFeebox = NULL;lv_obj_t *ui_BtnBackFbx = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_BtnNextFbx = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_LabelFbDown = NULL;lv_obj_t *ui_LabelFbUp = NULL;lv_obj_t *ui_LabelFbBwDown = NULL;lv_obj_t *ui_LabelFbBwUp = NULL;lv_obj_t *ui_LabelFbState = NULL;lv_obj_t *ui_LabelFbIPv4 = NULL;lv_obj_t *ui_LabelFbDevicesActive = NULL;lv_obj_t *ui_LabelFbDevicesTotal = NULL;
// event funtions
void ui_event_BtnBackFbx( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
}
}

void ui_event_BtnNextFbx( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      display_show_TABLE_FBX_DEVICES( e );
}
}

// build funtions

void ui_ScreenFreebox_screen_init(void)
{
ui_ScreenFreebox = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenFreebox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelFeebox = lv_label_create(ui_ScreenFreebox);
lv_obj_set_width( ui_LabelFeebox, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFeebox, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelFeebox,"FreeBox Pop");
lv_obj_remove_flag( ui_LabelFeebox, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_font(ui_LabelFeebox, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnBackFbx = lv_button_create(ui_ScreenFreebox);
lv_obj_set_width( ui_BtnBackFbx, 60);
lv_obj_set_height( ui_BtnBackFbx, 30);
lv_obj_set_align( ui_BtnBackFbx, LV_ALIGN_TOP_RIGHT );
lv_obj_set_ext_click_area(ui_BtnBackFbx, 10);
lv_obj_add_flag( ui_BtnBackFbx, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnBackFbx, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_BtnBackFbx);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Home");

ui_BtnNextFbx = lv_button_create(ui_ScreenFreebox);
lv_obj_set_width( ui_BtnNextFbx, 60);
lv_obj_set_height( ui_BtnNextFbx, 30);
lv_obj_set_align( ui_BtnNextFbx, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_ext_click_area(ui_BtnNextFbx, 10);
lv_obj_add_flag( ui_BtnNextFbx, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnNextFbx, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_BtnNextFbx);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Next");

ui_LabelFbDown = lv_label_create(ui_ScreenFreebox);
lv_obj_set_width( ui_LabelFbDown, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFbDown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFbDown, 150 );
lv_obj_set_y( ui_LabelFbDown, 210 );
lv_label_set_text(ui_LabelFbDown,"RX: -- Mb/s");
lv_obj_remove_flag( ui_LabelFbDown, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_LabelFbDown, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelFbDown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelFbDown, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelFbUp = lv_label_create(ui_ScreenFreebox);
lv_obj_set_width( ui_LabelFbUp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFbUp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFbUp, 150 );
lv_obj_set_y( ui_LabelFbUp, 225 );
lv_label_set_text(ui_LabelFbUp,"TX: -- Mb/s ");
lv_obj_remove_flag( ui_LabelFbUp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_LabelFbUp, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelFbUp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelFbUp, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelFbBwDown = lv_label_create(ui_ScreenFreebox);
lv_obj_set_width( ui_LabelFbBwDown, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFbBwDown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFbBwDown, 10 );
lv_obj_set_y( ui_LabelFbBwDown, 55 );
lv_label_set_text(ui_LabelFbBwDown,"Max RX: -- Mb/s");
lv_obj_remove_flag( ui_LabelFbBwDown, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags

ui_LabelFbBwUp = lv_label_create(ui_ScreenFreebox);
lv_obj_set_width( ui_LabelFbBwUp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFbBwUp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFbBwUp, 160 );
lv_obj_set_y( ui_LabelFbBwUp, 55 );
lv_label_set_text(ui_LabelFbBwUp,"Max TX: -- Mb/s ");
lv_obj_remove_flag( ui_LabelFbBwUp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags

ui_LabelFbState = lv_label_create(ui_ScreenFreebox);
lv_obj_set_width( ui_LabelFbState, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFbState, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFbState, 160 );
lv_obj_set_y( ui_LabelFbState, 30 );
lv_label_set_text(ui_LabelFbState,"State: -- ");
lv_obj_remove_flag( ui_LabelFbState, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags

ui_LabelFbIPv4 = lv_label_create(ui_ScreenFreebox);
lv_obj_set_width( ui_LabelFbIPv4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFbIPv4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFbIPv4, 10 );
lv_obj_set_y( ui_LabelFbIPv4, 30 );
lv_label_set_text(ui_LabelFbIPv4,"IP: --");
lv_obj_remove_flag( ui_LabelFbIPv4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags

ui_LabelFbDevicesActive = lv_label_create(ui_ScreenFreebox);
lv_obj_set_width( ui_LabelFbDevicesActive, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFbDevicesActive, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFbDevicesActive, 100 );
lv_obj_set_y( ui_LabelFbDevicesActive, 80 );
lv_label_set_text(ui_LabelFbDevicesActive,"Devices: --");
lv_obj_remove_flag( ui_LabelFbDevicesActive, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags

ui_LabelFbDevicesTotal = lv_label_create(ui_ScreenFreebox);
lv_obj_set_width( ui_LabelFbDevicesTotal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFbDevicesTotal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFbDevicesTotal, 180 );
lv_obj_set_y( ui_LabelFbDevicesTotal, 80 );
lv_label_set_text(ui_LabelFbDevicesTotal,"/ --");

lv_obj_add_event_cb(ui_BtnBackFbx, ui_event_BtnBackFbx, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnNextFbx, ui_event_BtnNextFbx, LV_EVENT_ALL, NULL);

}

void ui_ScreenFreebox_screen_destroy(void)
{
   if (ui_ScreenFreebox) lv_obj_del(ui_ScreenFreebox);

// NULL screen variables
ui_ScreenFreebox= NULL;
ui_LabelFeebox= NULL;
ui_BtnBackFbx= NULL;
ui_Label12= NULL;
ui_BtnNextFbx= NULL;
ui_Label13= NULL;
ui_LabelFbDown= NULL;
ui_LabelFbUp= NULL;
ui_LabelFbBwDown= NULL;
ui_LabelFbBwUp= NULL;
ui_LabelFbState= NULL;
ui_LabelFbIPv4= NULL;
ui_LabelFbDevicesActive= NULL;
ui_LabelFbDevicesTotal= NULL;

}
