// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#include "../ui.h"

lv_obj_t *ui_ScreenTable = NULL;lv_obj_t *ui_BtnBackTable = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_BtnNextTable = NULL;lv_obj_t *ui_Label8 = NULL;
// event funtions

// build funtions

void ui_ScreenTable_screen_init(void)
{
ui_ScreenTable = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenTable, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnBackTable = lv_button_create(ui_ScreenTable);
lv_obj_set_width( ui_BtnBackTable, 60);
lv_obj_set_height( ui_BtnBackTable, 30);
lv_obj_set_align( ui_BtnBackTable, LV_ALIGN_TOP_RIGHT );
lv_obj_set_ext_click_area(ui_BtnBackTable, 10);
lv_obj_add_flag( ui_BtnBackTable, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnBackTable, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_BtnBackTable);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Back");

ui_BtnNextTable = lv_button_create(ui_ScreenTable);
lv_obj_set_width( ui_BtnNextTable, 60);
lv_obj_set_height( ui_BtnNextTable, 30);
lv_obj_set_align( ui_BtnNextTable, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_ext_click_area(ui_BtnNextTable, 10);
lv_obj_add_flag( ui_BtnNextTable, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnNextTable, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_BtnNextTable);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Next");

}

void ui_ScreenTable_screen_destroy(void)
{
   if (ui_ScreenTable) lv_obj_del(ui_ScreenTable);

// NULL screen variables
ui_ScreenTable= NULL;
ui_BtnBackTable= NULL;
ui_Label11= NULL;
ui_BtnNextTable= NULL;
ui_Label8= NULL;

}
