// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: dashboard

#include "../ui.h"

lv_obj_t *uic_ScreenNAS;
lv_obj_t *ui_ScreenNAS = NULL;lv_obj_t *ui_LabelTitleNAS = NULL;lv_obj_t *ui_BtnBackNAS = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_BtnNextNAS = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_ArcNASCPU = NULL;lv_obj_t *ui_LabelNASCPU = NULL;lv_obj_t *ui_LabelTitleCPU = NULL;lv_obj_t *ui_ArcNASRAM = NULL;lv_obj_t *ui_LabelNASRAM = NULL;lv_obj_t *ui_LabelTitleRAM = NULL;lv_obj_t *ui_LabelNASTemp = NULL;lv_obj_t *ui_LabelNASVol = NULL;lv_obj_t *ui_LabelNASVolStatus = NULL;lv_obj_t *ui_LabelNASNetRx = NULL;lv_obj_t *ui_LabelNASNetTx = NULL;lv_obj_t *ui_LabelNASVolRead = NULL;lv_obj_t *ui_LabelNASVolWrite = NULL;
// event funtions
void ui_event_BtnBackNAS( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
}
}

void ui_event_BtnNextNAS( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      display_show_TABLE_NAS_DISKS( e );
}
}

// build funtions

void ui_ScreenNAS_screen_init(void)
{
ui_ScreenNAS = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenNAS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelTitleNAS = lv_label_create(ui_ScreenNAS);
lv_obj_set_width( ui_LabelTitleNAS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTitleNAS, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelTitleNAS,"Synology DS1522+");
lv_obj_remove_flag( ui_LabelTitleNAS, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_font(ui_LabelTitleNAS, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnBackNAS = lv_button_create(ui_ScreenNAS);
lv_obj_set_width( ui_BtnBackNAS, 60);
lv_obj_set_height( ui_BtnBackNAS, 30);
lv_obj_set_align( ui_BtnBackNAS, LV_ALIGN_TOP_RIGHT );
lv_obj_set_ext_click_area(ui_BtnBackNAS, 10);
lv_obj_add_flag( ui_BtnBackNAS, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnBackNAS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_BtnBackNAS);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Home");

ui_BtnNextNAS = lv_button_create(ui_ScreenNAS);
lv_obj_set_width( ui_BtnNextNAS, 60);
lv_obj_set_height( ui_BtnNextNAS, 30);
lv_obj_set_align( ui_BtnNextNAS, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_ext_click_area(ui_BtnNextNAS, 10);
lv_obj_add_flag( ui_BtnNextNAS, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnNextNAS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_BtnNextNAS);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Next");

ui_ArcNASCPU = lv_arc_create(ui_ScreenNAS);
lv_obj_set_width( ui_ArcNASCPU, 80);
lv_obj_set_height( ui_ArcNASCPU, 80);
lv_obj_set_x( ui_ArcNASCPU, 15 );
lv_obj_set_y( ui_ArcNASCPU, 30 );
lv_obj_remove_flag( ui_ArcNASCPU, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_value(ui_ArcNASCPU, 0);

lv_obj_set_style_pad_left(ui_ArcNASCPU, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ArcNASCPU, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ArcNASCPU, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ArcNASCPU, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelNASCPU = lv_label_create(ui_ArcNASCPU);
lv_obj_set_width( ui_LabelNASCPU, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNASCPU, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelNASCPU, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNASCPU,"--");

ui_LabelTitleCPU = lv_label_create(ui_ArcNASCPU);
lv_obj_set_width( ui_LabelTitleCPU, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTitleCPU, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelTitleCPU, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelTitleCPU,"CPU");
lv_obj_set_style_text_color(ui_LabelTitleCPU, lv_color_hex(0xAAFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTitleCPU, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTitleCPU, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcNASRAM = lv_arc_create(ui_ScreenNAS);
lv_obj_set_width( ui_ArcNASRAM, 80);
lv_obj_set_height( ui_ArcNASRAM, 80);
lv_obj_set_x( ui_ArcNASRAM, 110 );
lv_obj_set_y( ui_ArcNASRAM, 30 );
lv_obj_remove_flag( ui_ArcNASRAM, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_value(ui_ArcNASRAM, 20);

lv_obj_set_style_pad_left(ui_ArcNASRAM, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ArcNASRAM, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ArcNASRAM, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ArcNASRAM, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelNASRAM = lv_label_create(ui_ArcNASRAM);
lv_obj_set_width( ui_LabelNASRAM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNASRAM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelNASRAM, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNASRAM,"--");

ui_LabelTitleRAM = lv_label_create(ui_ArcNASRAM);
lv_obj_set_width( ui_LabelTitleRAM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTitleRAM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelTitleRAM, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelTitleRAM,"RAM");
lv_obj_set_style_text_color(ui_LabelTitleRAM, lv_color_hex(0x0088FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTitleRAM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTitleRAM, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNASTemp = lv_label_create(ui_ScreenNAS);
lv_obj_set_width( ui_LabelNASTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNASTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNASTemp, 220 );
lv_obj_set_y( ui_LabelNASTemp, 45 );
lv_label_set_text(ui_LabelNASTemp,"Temp: --°C");
lv_obj_remove_flag( ui_LabelNASTemp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_font(ui_LabelNASTemp, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNASVol = lv_label_create(ui_ScreenNAS);
lv_obj_set_width( ui_LabelNASVol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNASVol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNASVol, 220 );
lv_obj_set_y( ui_LabelNASVol, 65 );
lv_label_set_text(ui_LabelNASVol,"Vol: --%");
lv_obj_remove_flag( ui_LabelNASVol, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_font(ui_LabelNASVol, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNASVolStatus = lv_label_create(ui_ScreenNAS);
lv_obj_set_width( ui_LabelNASVolStatus, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_LabelNASVolStatus, LV_SIZE_CONTENT);   /// 10
lv_obj_set_x( ui_LabelNASVolStatus, 220 );
lv_obj_set_y( ui_LabelNASVolStatus, 85 );
lv_label_set_text(ui_LabelNASVolStatus,"Volume is --");
lv_obj_remove_flag( ui_LabelNASVolStatus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_font(ui_LabelNASVolStatus, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNASNetRx = lv_label_create(ui_ScreenNAS);
lv_obj_set_width( ui_LabelNASNetRx, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNASNetRx, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNASNetRx, 150 );
lv_obj_set_y( ui_LabelNASNetRx, 210 );
lv_label_set_text(ui_LabelNASNetRx,"RX: -- KB/s");
lv_obj_remove_flag( ui_LabelNASNetRx, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_LabelNASNetRx, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNASNetRx, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNASNetRx, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNASNetTx = lv_label_create(ui_ScreenNAS);
lv_obj_set_width( ui_LabelNASNetTx, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNASNetTx, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNASNetTx, 150 );
lv_obj_set_y( ui_LabelNASNetTx, 225 );
lv_label_set_text(ui_LabelNASNetTx,"TX: -- KB/s");
lv_obj_set_style_text_color(ui_LabelNASNetTx, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNASNetTx, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNASNetTx, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNASVolRead = lv_label_create(ui_ScreenNAS);
lv_obj_set_width( ui_LabelNASVolRead, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNASVolRead, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNASVolRead, 20 );
lv_obj_set_y( ui_LabelNASVolRead, 210 );
lv_label_set_text(ui_LabelNASVolRead,"Read: -- MB/s");
lv_obj_remove_flag( ui_LabelNASVolRead, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_LabelNASVolRead, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNASVolRead, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNASVolRead, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNASVolWrite = lv_label_create(ui_ScreenNAS);
lv_obj_set_width( ui_LabelNASVolWrite, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNASVolWrite, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNASVolWrite, 20 );
lv_obj_set_y( ui_LabelNASVolWrite, 225 );
lv_label_set_text(ui_LabelNASVolWrite,"Write: -- MB/s");
lv_obj_remove_flag( ui_LabelNASVolWrite, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_LabelNASVolWrite, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNASVolWrite, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNASVolWrite, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BtnBackNAS, ui_event_BtnBackNAS, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnNextNAS, ui_event_BtnNextNAS, LV_EVENT_ALL, NULL);
uic_ScreenNAS = ui_ScreenNAS;

}

void ui_ScreenNAS_screen_destroy(void)
{
   if (ui_ScreenNAS) lv_obj_del(ui_ScreenNAS);

// NULL screen variables
uic_ScreenNAS= NULL;
ui_ScreenNAS= NULL;
ui_LabelTitleNAS= NULL;
ui_BtnBackNAS= NULL;
ui_Label6= NULL;
ui_BtnNextNAS= NULL;
ui_Label2= NULL;
ui_ArcNASCPU= NULL;
ui_LabelNASCPU= NULL;
ui_LabelTitleCPU= NULL;
ui_ArcNASRAM= NULL;
ui_LabelNASRAM= NULL;
ui_LabelTitleRAM= NULL;
ui_LabelNASTemp= NULL;
ui_LabelNASVol= NULL;
ui_LabelNASVolStatus= NULL;
ui_LabelNASNetRx= NULL;
ui_LabelNASNetTx= NULL;
ui_LabelNASVolRead= NULL;
ui_LabelNASVolWrite= NULL;

}
